### PR TITLE
fix nullable return type definitions

### LINKED ISSUE #241: incomplete Typescript definitions for nullable methods return type
Today I came across some "null pointer" errors while trying to read some metadata from a zipped shapefile.

Our application was coded to expect user inputted zip files as a zipped shapefile, but sometimes the user mistakenly uploads it without a .shp file inside, which makes it technically an invalid shapefile, but the 'ESRI Shapefile' driver still opens the dataset and layer sucessfully, as it would with a dbf. More specifically, it opens a layer with all the attributes, but null values for the geometry, I understand that is expected behavior, as that is also how many GIS sofwares treat .dbf files, like QGIS and ArcGIS, and it that is also how some other parts of our application read dbf files, actually.

At the end of the day, the problem seems to boil down to this lib's built-in typescript type definitions, as the `Feature.getGeometry()` method should be defined as `Geometry | null` return type instead of just `Geometry`, because that's the actual runtime behavior ([ref](https://github.com/mmomtchev/node-gdal-async/blob/772be1df2c4924ed7fc3c07212fc51807c342e97/src/gdal_feature.cpp#L181)) , same for `Layer.srs`, which should be typed as `SpatialReference | null`.

**I'd be glad to contribute with a pull request**, I've learned from the CHANGELOG file that this project uses documentation-polyglot to copy the jsdoc comments from the cpp source code, **are you accepting contributions**? 

Today we're having to resort to type casts, but that's not an ideal solution.

### PR DESCRIPTION
**Pull request by pumpkinlink**
closes #241

### CODE REVIEW

File: src/gdal_layer.cpp [hunk 1]
```diff
@@ -411,7 +411,7 @@ NAN_GETTER(Layer::dsGetter) {
  * @name srs
  * @instance
  * @memberof Layer
- * @type {SpatialReference}
+ * @type {SpatialReference|null}
```
Comment (mmomtchev) [inline src/gdal_layer.cpp:414]: You will have to change the affected tests to this form:

```ts
const geom = feature.getGeometry()
assert.isNotNull(geom)
assert.isFalse(geom.isEmpty())
```

Comment (pumpkinlink) [reply src/gdal_layer.cpp:414]: added missing  asserts for Feature.getGeometry(), Layer.srs, MDArray.srs and RasterBand.getMaskBand()

**Comment by mmomtchev** [comment]
You are still posting simultaneously related to the sexually motivated extortion with the French police
